// Writes the tiny loader that lives inside JARVIS.app (Contents/Resources/app).
//
// The app bundle is only a launcher: it starts JARVIS from this checkout, so an
// update (git pull + build) takes effect without reinstalling the app. Launched
// from the Dock, apps get a minimal PATH — node, git and Homebrew are added back.
//
//   node scripts/mac-app/bootstrap.mjs <Resources/app directory>
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");

export function writeBootstrap(dir, { checkout = root, nodeDir = path.dirname(process.execPath) } = {}) {
  mkdirSync(dir, { recursive: true });
  // Same package name as apps/desktop: same settings folder and single-instance lock.
  writeFileSync(
    path.join(dir, "package.json"),
    `${JSON.stringify({ name: "@jarvis/desktop", private: true, main: "main.js" }, null, 2)}\n`,
  );
  const main = `// Generated by scripts/install-mac-app.sh — do not edit; reinstall instead.
const path = require("node:path");
const checkout = ${JSON.stringify(checkout)};
process.env.JARVIS_APP = "1";
process.env.PATH = [${JSON.stringify(nodeDir)}, "/opt/homebrew/bin", "/usr/local/bin", process.env.PATH || "/usr/bin:/bin:/usr/sbin:/sbin"].join(path.delimiter);
try {
  require(path.join(checkout, "apps", "desktop", "dist-electron", "main.js"));
} catch (error) {
  const { app, dialog } = require("electron");
  dialog.showErrorBox(
    "JARVIS can't start",
    "JARVIS runs from " + checkout + ", but it isn't there or isn't built.\\n\\n" +
      "Run scripts/install-mac-app.sh in that folder again.\\n\\n" + String(error && error.message),
  );
  app.exit(1);
}
`;
  writeFileSync(path.join(dir, "main.js"), main);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const target = process.argv[2];
  if (!target) {
    console.error("usage: node scripts/mac-app/bootstrap.mjs <directory>");
    process.exit(2);
  }
  writeBootstrap(path.resolve(target));
}
